language: php
dist: focal

php:
  - 7.4
  - 8.0
  - 8.1.0

git:
  depth: 150

cache:
  directories:
    - vendor

install:
  - phpenv config-rm xdebug.ini

before_script:
  - composer install -n

script:
  - vendor/bin/phpcs
  - vendor/bin/phpstan analyse -c phpstan.neon.dist
  - vendor/bin/phpunit
